version: "3"

services:
  db:
    image: postgres
  lotsizing:
    build: .
    command: python manage.py devserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
